name: Remind PR to main

on:
  push:
    branches:
      - dev

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Comment reminder
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'main',
              sort: 'updated',
              direction: 'desc'
            });
            
            if (pullRequests.length > 0) {
              const pr = pullRequests[0];
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: "New commits have been pushed to 'dev'. Please consider updating this PR."
              });
            } else {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "Reminder: New commits pushed to 'dev'",
                body: "New commits have been pushed to 'dev'. Consider opening a PR to 'main'."
              });
            }
